version: "3.7"
services:
  mogac-mogac-db:
    platform: linux/x86_64    # 추가된 라인
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mogac-mogac
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=mogac
      - MYSQL_PASSWORD=1234
      - TZ=UTC
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./mysql:/var/lib/mysql