server:
  port: 64412 # 서버의 포트 번호, 위와 동일하다
  shutdown: graceful
  servlet:
    context-path: /api

spring:
  application:
    name: user-service # 애플리케이션 서버의 이름 , 위와 동일하다
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 52918629712-48on58rmu4dtatok51p67cbcncipf17u.apps.googleusercontent.com
            client-secret: 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
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile
              - email
          naver:
            client-id: XZV_4BQxsFKPalXl9GtV
            client-secret: SpXf2nkJnN
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile
          kakao:
            client-id: 291bd18002d75830b35ecbacf93cad6c
            client-secret: TbuYKwSkkz82Ydufg1B8CNhwZzIPSNXG
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile
              - account_email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            unlink-uri: https://accounts.google.com/o/oauth2/revoke
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            unlink-uri: https://nid.naver.com/oauth2.0/token
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            unlink-uri: https://kapi.kakao.com/v1/user/unlink

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/mogac-mogac?serverTimezone=UTC&characterEncoding=UTF-8
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234

jwt:
  secretKey: secret-key #jwt-secret-key
  signatureAlgorithm: HS256
  tokenExpired: 604800 #(sec) 7 days
client:
  origins: http://localhost:3000
#eureka:
#  client:
#    register-with-eureka: true  # 이번에는 해당 서비스가 클라이언트로 인식되어야 하므로 true로 해주자
#    fetch-registry: true  # 이번에는 해당 서비스가 클라이언트로 인식되어야 하므로 true로 해주자
#    service-url:
#      defaultZone: http://localhost:8761/eureka # eureka server 가 위치하고 있는 기본 주소를 적어줄 수 있다.